version: '3'
services:    
  selenium-hub:         
    image: selenium/hub    
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=60
      - SE_SESSION_RETRY_INTERVAL=5
    ports:             
      - "4442-4444:4442-4444"                   
    networks:           
      - grid  

  node-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment: 
      - SE_EVENT_BUS_HOST=selenium-hub 
      - SE_EVENT_BUS_PUBLISH_PORT=4442 
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 
      - SE_NODE_MAX_SESSIONS=1  
    ports:
      - "5900:5900"  # For VNC access
    networks:           
      - grid 

  node-firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment: 
      - SE_EVENT_BUS_HOST=selenium-hub 
      - SE_EVENT_BUS_PUBLISH_PORT=4442 
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 
      - SE_NODE_MAX_SESSIONS=1 
    ports:
      - "5901:5900"  # For VNC access
    networks:           
      - grid 

networks:
  grid:
    driver: bridge
